sudo: false
addons:
  apt:
    packages:
      - gperf
compiler:
  - gcc
  - clang
env:
  matrix:
    - MRUBY_VERSION=master
    - MRUBY_VERSION=1.2.0
    - MRUBY_VERSION=1.3.0
script:
  - export MRUBY_CONFIG="$TRAVIS_BUILD_DIR/.travis_config.rb"
  - 'if [ "$MRUBY_VERSION" = "master" ] ; then
      git clone --depth 1 "https://github.com/mruby/mruby.git" mruby-$MRUBY_VERSION;
    else
      curl -L "https://github.com/mruby/mruby/archive/$MRUBY_VERSION.tar.gz" > mruby-$MRUBY_VERSION.tar.gz;
      tar xf mruby-$MRUBY_VERSION.tar.gz;
    fi'
  - cd mruby-$MRUBY_VERSION
  - ./minirake all test
